### ISSUE TITLE
Update API on request to import an analysis by a user who does not have access to a study (user dataset or regular study: private/prerelease)

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaUserService#21]
This is to improve the UX when a user who has received an analysis URL from another user sharing it, does not have access to the study  (user dataset or regular study: private/prerelease):
The behavior should be the same for a user dataset and a regular study:
(1) send back a sentence and study id "Sorry, you do not have currently access to this study (are you logged in?). Please request permission to access the study, and then try again to import the analysis with your URL." 
(2) do not save the analysis in the user database

**Comment by ryanrdoherty** [comment]
@dmfalke What kind of API do you want here?  Thinking a 403 Forbidden with JSON like this:
```
{
  studyId: string,
  errorMessage: string, the value above that Cristina wrote
}
```

**Comment by ryanrdoherty** [comment]
@aurreco-uga What level of permissions are required to copy an analysis?  Options are:
```
  private final boolean _allowStudyMetadata;
  private final boolean _allowSubsetting;
  private final boolean _allowVisualizations;
  private final boolean _allowResultsFirstPage;
  private final boolean _allowResultsAll;
```
I believe these are always progressive, so a higher perm implies lower perms.  I'm thinking we probably can allow the share even as long as subsetting is allowed?  Or do they need visualizations too?  Maybe both since an analysis may contain visualizations?
